
# The name of the app. Must be unique within a project.
name: app

# The type of the application to build
type: 'nodejs:16'

# Turn off the default use of npm
build:
    flavor: none

# Include yarn as a global dependency
dependencies:
    nodejs:
        yarn: "1.22.19"

# The size of the persistent disk of the application (in MB)
disk: 512

# Your app's configuration when it's exposed to the web.
web:
    locations:
        '/':
            # The public directory relative to the app root.
            root: 'src'
            # Forward resources to the app.
            passthru: true
            # What files to use when serving a directory.
            index: ["server.ts"]
            # Allow files even without specified rules.
            allow: true
    commands:
        start: npm run start